# Generated by Django 5.2.10 on 2026-02-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_productos_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='precio',
        ),
        migrations.AddField(
            model_name='productos',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio de Compra'),
        ),
        migrations.AddField(
            model_name='productos',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio de Venta'),
        ),
    ]
