# Generated by Django 5.2.10 on 2026-03-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_productos_precio_productos_precio_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='categoria',
            field=models.CharField(choices=[('papa_primera', 'Papa Primera'), ('tronco', 'Tronco'), ('medio_pollo', 'Medio Pollo'), ('pelona', 'Pelona'), ('rechazo_grueso', 'Rechazo Grueso'), ('rechazo_medio', 'Rechazo Medio'), ('tercera', 'Tercera'), ('sobrante', 'Sobrante'), ('otros', 'Otros')], default='otros', max_length=20, verbose_name='Categoría'),
        ),
    ]
