# Generated by Django 6.0.2 on 2026-02-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_clientes_delete_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='clientes',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
