# Generated by Django 6.0.4 on 2026-05-01 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_clientes_inicial_clientes_saldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='telefono',
        ),
    ]
