# Generated by Django 5.2.10 on 2026-05-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_clientes_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
