# Generated by Django 6.0.2 on 2026-02-16 03:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajadores',
            fields=[
                ('idTrabajador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=22)),
                ('cargo', models.CharField(choices=[('gerente', 'Gerente'), ('vendedor', 'Vendedor'), ('cajero', 'Cajero'), ('almacenista', 'Almacenista'), ('repartidor', 'Repartidor'), ('limpieza', 'Personal de Limpieza'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('salario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
