# Generated by Django 5.2.10 on 2026-02-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_semana_actual', models.DateField(verbose_name='Inicio Semana Actual')),
                ('dias_por_semana', models.IntegerField(default=8, verbose_name='Días por Semana')),
            ],
            options={
                'verbose_name': 'Configuración de Semana',
                'verbose_name_plural': 'Configuración de Semanas',
            },
        ),
        migrations.CreateModel(
            name='LiquidacionSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_semana', models.IntegerField(verbose_name='Número de Semana')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin')),
                ('fecha_liquidacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Liquidación')),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Ingresos')),
                ('total_ventas_completo', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ventas Pago Completo')),
                ('total_ventas_credito', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ventas a Crédito')),
                ('total_recaudado', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Recaudado')),
                ('cobrado_de_creditos', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Cobrado de Créditos')),
                ('total_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Gastos')),
                ('total_ganancia', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ganancia Total')),
                ('balance_final', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Balance Final')),
                ('cantidad_ventas', models.IntegerField(default=0, verbose_name='Cantidad de Ventas')),
                ('cantidad_ventas_completo', models.IntegerField(default=0, verbose_name='Cantidad Ventas Completo')),
                ('cantidad_ventas_credito', models.IntegerField(default=0, verbose_name='Cantidad Ventas Crédito')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Liquidación Semanal',
                'verbose_name_plural': 'Liquidaciones Semanales',
                'ordering': ['-fecha_liquidacion'],
                'unique_together': {('numero_semana', 'anio')},
            },
        ),
    ]
