# Generated by Django 5.2.10 on 2026-02-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelprincipal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsemana',
            name='dias_por_semana',
            field=models.IntegerField(default=7, verbose_name='Días por Semana'),
        ),
        migrations.AlterField(
            model_name='configuracionsemana',
            name='fecha_inicio_semana_actual',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio Semana Actual'),
        ),
    ]
