# Generated by Django 6.0.2 on 2026-02-15 23:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gastos',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='gastos',
            name='categoria',
            field=models.CharField(choices=[('operativo', 'Operativo'), ('personal', 'Personal'), ('insumos', 'Insumos'), ('transporte', 'Transporte'), ('servicios', 'Servicios'), ('mantenimiento', 'Mantenimiento'), ('otros', 'Otros')], default='otros', max_length=20),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
