# Generated by Django 6.0.2 on 2026-02-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_alter_gastos_options_gastos_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='categoria',
            field=models.CharField(choices=[('administracion', 'Administración de la Empresa'), ('trabajadores', 'Trabajadores'), ('comercio_productos', 'Comercio y Productos'), ('otros', 'Otros')], default='otros', max_length=20),
        ),
    ]
