# Generated by Django 6.0.2 on 2026-02-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado_pago',
            field=models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente'), ('vencido', 'Vencido')], default='pagado', max_length=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_pago',
            field=models.CharField(choices=[('completo', 'Pago Completo'), ('fiado', 'Pago a Crédito')], default='completo', max_length=10),
        ),
    ]
