# Generated by Django 5.2.10 on 2026-02-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_venta_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='ganancia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ganancia Total'),
        ),
        migrations.AddField(
            model_name='venta',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio de Compra (unitario)'),
        ),
        migrations.AddField(
            model_name='venta',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio de Venta (unitario)'),
        ),
    ]
