# Generated by Django 5.2.10 on 2026-05-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_venta_metodo_pago_alter_venta_producto_detalleventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='monto_efectivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto en Efectivo'),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_transferencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto por Transferencia'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('mixto', 'Efectivo + Transferencia'), ('fiado', 'A Crédito'), ('efectivo_fiado', 'Efectivo + Crédito'), ('transferencia_fiado', 'Transferencia + Crédito'), ('mixto_fiado', 'Efectivo + Transf. + Crédito')], default='efectivo', max_length=25, verbose_name='Método de Pago'),
        ),
    ]
