# Generated by Django 6.0.4 on 2026-05-09 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(choices=[('Clientes', 'Clientes'), ('Proveedores', 'Proveedores'), ('Productos', 'Productos'), ('Ventas', 'Ventas'), ('Gastos', 'Gastos')], max_length=50, unique=True)),
                ('auditar_creacion', models.BooleanField(default=True)),
                ('auditar_edicion', models.BooleanField(default=True)),
                ('auditar_eliminacion', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración de Auditoría',
                'verbose_name_plural': 'Configuraciones de Auditoría',
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('pagar', 'Pagar/Abonar'), ('saldar', 'Saldar Deuda'), ('cambio_estado', 'Cambio de Estado')], help_text='Tipo de acción realizada', max_length=20)),
                ('id_objeto', models.PositiveIntegerField(help_text='ID del objeto afectado')),
                ('modelo', models.CharField(help_text='Nombre del modelo para referencia rápida', max_length=50)),
                ('descripcion_objeto', models.CharField(help_text='Descripción legible del objeto (ej: nombre del cliente)', max_length=255)),
                ('valores_antes', models.JSONField(blank=True, default=dict, help_text='Valores del objeto antes del cambio')),
                ('valores_despues', models.JSONField(blank=True, default=dict, help_text='Valores del objeto después del cambio')),
                ('campos_modificados', models.JSONField(blank=True, default=list, help_text='Lista de campos que fueron modificados')),
                ('detalles', models.TextField(blank=True, help_text='Detalles adicionales de la acción (ej: motivo de pago, monto)')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la acción')),
                ('ip_cliente', models.GenericIPAddressField(blank=True, help_text='IP del cliente que realizó la acción', null=True)),
                ('tipo_contenido', models.ForeignKey(help_text='Tipo de modelo afectado', on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['-fecha_hora'], name='auditoria_r_fecha_h_be190c_idx'), models.Index(fields=['usuario', '-fecha_hora'], name='auditoria_r_usuario_0c1b0a_idx'), models.Index(fields=['modelo', '-fecha_hora'], name='auditoria_r_modelo_95eace_idx'), models.Index(fields=['accion', '-fecha_hora'], name='auditoria_r_accion_96f4bb_idx')],
            },
        ),
    ]
