# Generated by Django 6.0.4 on 2026-05-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0003_limpiar_auditoria_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='accion',
            field=models.CharField(choices=[('crear', 'Creación'), ('editar', 'Edición'), ('eliminar', 'Eliminación'), ('pagar', 'Pago/Abono'), ('saldar', 'Saldar Deuda'), ('cambio_estado', 'Cambio de Estado')], help_text='Tipo de acción realizada', max_length=20),
        ),
    ]
